sudo: required
language: node_js
branches:
  only:
  - develop
  - master
  - "/^v(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
git:
  depth: 1
node_js:
- '0.12'
cache:
  directories:
  - "~/.meteor"
before_install:
- npm install -g npm@'>=2.13.5'
- mkdir -p node_modules
install:
- curl https://install.meteor.com | /bin/sh
before_script:
- mkdir /tmp/build
script:
- meteor build /tmp/build
before_deploy:
- source ".travis/setbranch.sh"
- source ".travis/setdeploydir.sh"
- ".travis/setupsig.sh"
- ".travis/namefiles.sh"
- ".travis/sandstorm.sh"
deploy:
  provider: releases
  api_key:
    secure: SLtbGv9vL6qC3rKGwKuXfUSFuRCeLsBFiRA1nBDWoyua7F3rLy8fBvhS3sXRDCqAF6hJgXQwZzX2pS1Lljwjjmwi/80Ns7VDtreX5QstHukFAxaJh2E0Lz5zQdSqAb61KdAipZmYfp2fgCr8T+xztE/mvtPD5R8CcIQIjJpl9rh+mrkkshkcaNOY4JQrqyrcTeCOeBQMXTZSkkbdJr4gb9++A2c61K0txfid9+VwqGm5MwvaT80JC5wLQkL8rS9OUcNJHFf90ELFZpRZnZnI2lsfmTBAxRKL994UZgzru3XNMhUTsJPh7OyVn/xSlyjLcvsn4dSon1PE9t3RkuxsbTxx/XY+gIkXSGl38jZlhextaJoV0gTFkEg33tF/aZ4+I+iZM8LYfRAoUuZU0fSzGnFtFZp4xptF2ECLKmI/3dmuE6iwr+G1xUer9g2Rq9fXXrHgUA164544IdY4aDisxd9U78U0K7WaPtbvphiVl4GbgVnfTEgNVdpXcQxUtcXPZMiBRz5+E+1fExmCfO6+7mZ/yzDrsFYoRdmuo1SMGRI4iqb5jl/PImZ9ukTqRmQdqd3WJp3zzPbIEJPwhMtS5LMxzBMSfugXwjEajkXybcH5CWQ7jo+ogNqcM/CcJ3q4ahYuLTN7VeZWZ8h5kwr9bPxPooZuhWw0WPRa+XUM22o=
  file:
  - "$ROCKET_DEPLOY_DIR/rocket.chat-$ROCKET_BRANCH.tgz"
  - "$ROCKET_DEPLOY_DIR/rocket.chat-$ROCKET_BRANCH.tgz.asc"
  - "$ROCKET_DEPLOY_DIR/rocket.chat-$ROCKET_BRANCH.spk"
  on:
    tags: true
    all_branches: true
after_deploy:
- ".travis/docker.sh"
env:
  global:
  - secure: y9LYMUBDtiAUlIwJEvubBrYLVrjPsPg7ClY5HcFisdm7OwOzMqHcjTFX8Sj2tN/6IXNcZLqFOhHcwuSdM0uUbBIDooTVnwMVSIy6ExZFOaZNrvAf/Axf2k6p15iAmtPmVo7o+us5SRVRQvuP6GqdUPMYIYn71jHrrjUKQp3/hgRZBlpIn7dyPs5WuLVXZda5hVjIjJpSfK1RZDoGd/b7o8jywvFgSdvBiB+lX1VXCVisRJU9yS28CGIcpoxeQg9AFk4Uez6+8+b/koLp3imQddY9VjYyYx2D8fNxRcUujUHux24VG5MSzQRtJh9JwLlJ+pyAN1KUSvoam6R3MQGoKJg0AH3UxikmSQ4yGZwsSkPSqWbRCRgSVmNtq/YLuTJjQEUHmMCxXUb53HdJisAaxaQiOfg/IfqMVtUWeeIfSDDNEhO9WgpuNvf4fOltdwlL2N1YwubR/fGw8/W/to9jSu94FxJHw6c2V4KQOJqq1XA+KtwMMYak82NjfS2DIhcwyf4EaKagkg4HD3z5BYpuxQdeQnkQkvvkvkI26kV+jPkqUGRlejS7AXG4PrhcUUf/nBvvWjUFrLwvk+epkMP3D2k94r2XUl7apyrANTfyTVyOCc1ogUu9N2XC4ShF2uxu5hoNxk+hNTo1D7uSrFE7aM1GpDFRPOUjtpt2E0mqOoQ=
  - secure: UzXkeAMYzlEyncgUtos6/mwjUc3uMRT+1c6XzjdCBXaA/WkJoWH6KgZni1SSc/fS/LsvlVOb/8TusokUcIIup+BvQ7/GIoe17XqODG9nflmfJI6nXRK79D+Ux1N/coHKIIq+byyvYYp0jYptxL3M5YfOVp0gRffhO17cKxUknjjD4rVjro5FCmQw+sEbAmU+bMBjiWt6XqPnaxQa3QYIvDBqnBTqOl24iNUEEckBTJsYxTYTAh3r423Lh//K0ae/Hz8FEclBMGwwwr4gAwFUXS2ipkh7iJUEy/kp33/+Ivb6GqhigCMOry7t9Flfvd6t8usdB3K7pqrIfpKXZ8Y292meG4F7SwmQiRp23vxCKWvFqrnQMDqeK4NuoemobxaFhiAyN3mdY1gl8dDiAjowylIz4/lw8WY9XCDwUsrYNXd3NZ5B0H8F+DLW0y541Q89suD4kfdtQtKLfHWjEZjPLSvz5zMZcJGt1AMOOFGFk4e6JJ1zJpIhLBdqCnaC0lW29EbaadT3gKldmaj2Ru6M783H3sL8gmyLs/0SdM8dUuA7HdpTWHI/KhJAQyPdMz6/kq8wyd1iN8t1p3wjmth89Et9HecYDAW3uelxoiR9Um5nm33w41Ukv+AOlEyheNT1uure+iMelXZJZVP0/9AZqxDEsALaARa4JhHEEOkniO0=
