version: "3.2"

networks:
  otel:

services:
  loki:
    image: grafana/loki:latest
    volumes:
      - ./data/loki/chunks:/loki/chunks
      - ./data/loki/rules:/loki/rules
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    user: "0"
    networks:
      - otel

  tempo:
    image: grafana/tempo:latest
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    command: [ "-config.file=/etc/tempo.yaml" ]
    user: "0"
    volumes:
      - ./data/tempo/wal:/var/tempo/wal
      - ./data/tempo/blocks:/var/tempo/blocks
      - ./config/tempo-config.yaml:/etc/tempo.yaml
    networks:
      - otel

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
    volumes:
      - ./config/prometheus-config.yaml:/etc/prometheus.yaml
    user: "0"
    networks:
      - otel

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch
    image: grafana/grafana:latest
    ports:
      - "3600:3000"
    depends_on:
      - tempo
      - loki
      - prometheus
    user: "0"
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - otel

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - tempo
      - loki
      - prometheus
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - otel
