name: Stale Questions

on:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  no-response:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 10
        days-before-close: 4
        only-labels: 'stat: need more info,stat: waiting response'
        stale-issue-message: >-
          This issue has been marked as stale because there has been
          no further activity in the last 10 days. If the issue remains
          stale for the next 4 days (a total of two weeks with no activity),
          then it will be assumed that the question has been resolved and
          the issue will be automatically closed.
        stale-issue-label: 'stat: no response'
        operations-per-run: 40
