name: Stale Questions

on:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  no-response:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.19
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 10
        days-before-close: 4
        only-labels: 'stat: need more info'
        stale-issue-message: >-
          This issue has been marked as stale because there has been
          no further activity in the last 10 days. If the issue remains
          stale for the next 4 days (a total of two weeks with no activity),
          then it will be assumed that the question has been resolved and
          the issue will be automatically closed.
        stale-issue-label: 'stat: no response'
        operations-per-run: 40

#   stale:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/stale@v3.0.19
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         days-before-stale: 60
#         days-before-close: 7
#         exempt-issue-labels: 'Epic,Feature: Planned,sla,sponsored,stat: waiting PR merge,Triaged,subj: security'
#         stale-issue-message: >-
#           This issue has been automatically marked as stale because it has not had
#           recent activity. It will be closed if no further activity occurs. Thank you
#           for your contributions.
#         stale-issue-label: 'stat: stale'
#         operations-per-run: 40
