name: Github vulnerabilities and jira board integration

on:
  schedule:
    - cron: '0 1 * * *'
      
jobs:
  IntegrateSecurityVulnerabilities:
    runs-on: ubuntu-22.04
    steps:
      - name: "Github vulnerabilities and jira board integration"
        uses: RocketChat/github-vulnerabilities-jira-integration@v0.3
        env:
          JIRA_URL: https://rocketchat.atlassian.net/
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          JIRA_EMAIL: security-team-accounts@rocket.chat
          JIRA_PROJECT_ID: GJIT
          UID_CUSTOMFIELD_ID: customfield_10059
          JIRA_COMPLETE_PHASE_ID: 31
          JIRA_START_PHASE_ID: 11
          
